spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warranty_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8&useUnicode=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Kafka Configuration (optional - comment out if Kafka is not running)
  # kafka:
  #   bootstrap-servers: localhost:9092
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #     acks: all
  #     retries: 3
  #   consumer:
  #     group-id: warranty-service-group
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  #     auto-offset-reset: earliest
  #     properties:
  #       spring.json.trusted.packages: "com.shoppro.warranty"

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

logging:
  level:
    com.shoppro.warranty: DEBUG
    org.springframework.kafka: INFO
    org.springframework.security: INFO
