package com.example.notification.entity;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_CONFIRMED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    PRODUCT_IN_STOCK,
    PRODUCT_OUT_OF_STOCK,
    PRICE_DROP,
    PROMOTION,
    ACCOUNT_VERIFICATION,
    PASSWORD_RESET,
    SECURITY_ALERT,
    SYSTEM_MAINTENANCE,
    WELCOME,
    BIRTHDAY,
    CART_ABANDONMENT,
    REVIEW_REMINDER,
    WARRANTY_UPDATE,
    SUPPORT,
    CUSTOM
}
